services:
  app:
    image: php:8.3-fpm
    container_name: app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: web
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
